version: '3'
services:
  angular-interface:
    build:
      context: ./angular-interface
    ports:
      - "8080:80" 
    depends_on:
      - flask-gateway

  flask-gateway:
    build:
      context: ./flask-gateway
    ports:
      - "5000:5000"
    #volumes:
    #  - ./my_test_data:/app/saved_metadata # Mount host directory to container

