structure: fred
whitelist_repository: https://github.com/loosolab/FRED_whitelists
private_access:
  name: null
  token: null
branch: main
whitelist_path: fred
update_whitelists: true
output_path: .
filename: _metadata
email: example@email.de
