structure: fred
whitelist_repository: https://gitlab.gwdg.de/loosolab/software/metadata_whitelists.git
private_access:
  name: null
  token: null
branch: v1.2.*
whitelist_path: fred
update_whitelists: true
output_path: .
filename: _metadata
email: bcu.support@mpi-bn.mpg.de
